### ISSUE TITLE
Consents posted manually aren't being persisted by the SDK

### ISSUE THREAD

**Issue by ThiagoFerrao** [cookie-information/ios-release#1]
### Issue
Consents posted manually aren't being persisted by the SDK.

### SDK Version
1.1.0

### Background
When creating the `Consent` data model used as a parameter to the method `postConsent`, in the sdk version 1.1.0  isn't possible to set its `userConsents` value due to its initializer `internal init(consentItem: ConsentItem, isSelected: Bool)` being internal.
Since `saveConsentResult`, as seen below, only uses the `userConsents` parameter when persisting data, the user's consents won't be saved when posting the consents manually.

```swift
extension MobileConsents {
    func saveConsentResult(_ consent: Consent) {
        let consents = consent.userConsents
        localStorageManager.addConsentsArray(consents, versionId: consent.consentSolutionVersionId)
    }
}
```

**Comment by stonecrumbler** [comment]
Fixed in version 1.2.1
