### ISSUE TITLE
privacy manifest 

### ISSUE THREAD

**Issue by sbo-nemlig** [cookie-information/ios-release#11]
Will your SDK add privacy manifest  as Apple requires   ?https://developer.apple.com/documentation/bundleresources/privacy_manifest_files

**Comment by stonecrumbler** [comment]
@sbo-nemlig we're investigating the topic and get back to you shortly

**Comment by stonecrumbler** [comment]
@sbo-nemlig in an upcoming release of our SDK we will add the manifest.

**Comment by stonecrumbler** [comment]
fixed in version 1.5.5
