### ISSUE TITLE
privacyDescription exceed safe area

### ISSUE THREAD

**Issue by marekmeissner** [cookie-information/ios-release#15]
` privacyDescription.trailingAnchor.constraint(equalTo: view.trailingAnchor)`

privacyDescription with longer texts exceed safe area on horizontal mode and has inconsistent margin on portrait mode.

Currently:
![Simulator Screenshot - iPhone 15 - 2024-02-28 at 13 43 33](https://github.com/cookie-information/ios-release/assets/51102935/20d23f0c-2a32-40c8-97ea-4fdf93e48d9d)

Solution:
I propose we include layoutMarginsGuide to trailing anchor constraint so text aligns according to layout margins, and not directly to the edge of a view which causes readability and design problems

` privacyDescription.trailingAnchor.constraint(equalTo: view.layoutMarginsGuide.trailingAnchor)`

After changes:
![Simulator Screenshot - iPhone 15 - 2024-02-28 at 14 08 41](https://github.com/cookie-information/ios-release/assets/51102935/0c01a171-48bd-4f9a-b45d-2005d64b0879)

**Comment by stonecrumbler** [comment]
fixed in version 1.5.3
