### ISSUE TITLE
Error case not handling completion block

### ISSUE THREAD

**Issue by ROMANiak45** [cookie-information/ios-release#3]
https://github.com/cookie-information/ios-release/blob/59ac7d83d144d90d32f3419e31c47db75fb30d83/Sources/MobileConsentsSDK/UI/PopUp/PrivacyPopUpViewModel.swift#L106

In case of error the completion will never be executed, as view dismissal is handled in by the viewModel and not by the router that handles the completion block.
Overriding the router nor the viewModel can't be performed as classes are marked as final

**Comment by stonecrumbler** [comment]
@ROMANiak45 thanks for the feedback, we've discussed this issue and will address it in the upcoming major release 2.0.0.

**Comment by HenrikBacher** [comment]
@andy-3000 do you have an expectation for when 2.0 will be released?

**Comment by HenrikBacher** [comment]
Any updates on this issue?

**Comment by HenrikBacher** [comment]
Which release is this fixed in? @andy-3000
