### ISSUE TITLE
Consent switch control stores data from previous user

### ISSUE THREAD

**Issue by ROMANiak45** [cookie-information/ios-release#6]
In scenario user A first time logs in, selects all, then logs out, then user B first time logs in all switches are set to on

**Comment by stonecrumbler** [comment]
The SDK is not aware of the user sessions in the app, however, calling the `removeStoredConsents` method at logout will get rid of the stored consents and the newly logged in user will start with a clean slate.

**Comment by ROMANiak45** [comment]
@andy-3000 what happens in case the same user logs in again, his consent is also reset?

**Comment by stonecrumbler** [comment]
> @andy-3000 what happens in case the same user logs in again, his consent is also reset?

Yes, the consents get reset. The SDK has no multi-user support as of now. We may consider it in the future.

**Comment by ROMANiak45** [comment]
got it and thanks :)
