### ISSUE TITLE
Compile error in version 1.4.0 - reference in closure requires explicit use of 'self'

### ISSUE THREAD

**Issue by SimonLauridsen** [cookie-information/ios-release#9]
I can't compile the latest release of the MobileConsentsSDK because of the property "router" is being referenced inside a closure. The issue is found in the PrivacyPopUpViewModel in the method: "loadConsentSolution".

`
private func loadConsentSolution() {
        onLoadingChange?(true)
        
        consentSolutionManager.loadConsentSolutionIfNeeded { [weak self] result in
            guard let self = self else { return }
            
            self.onLoadingChange?(false)
            
            guard case .success(let solution) = result else {
                if case let .failure(error) = result {
                    router?.closeAll(error: error) <--- THE ERROR IS ON THIS LINE
                }
                return
            }
            
            let title = solution.templateTexts.privacyCenterTitle.primaryTranslation().text
            
            
            let optionalSection = PopUpConsentsSection(viewModels: self.consentViewModels(from: solution))
            let requiredSection = PopUpConsentsSection(viewModels: self.consentViewModels(from: solution, required: true))
            
            let data = PrivacyPopUpData(
                title: title,
                sections: [
                    requiredSection,
                    optionalSection
                ],
                acceptAllButtonTitle: solution.templateTexts.acceptAllButton.primaryTranslation().text,
                saveSelectionButtonTitle: solution.templateTexts.acceptSelectedButton.primaryTranslation().text,
                privacyDescription: solution.consentItems.first { $0.type == .privacyPolicy}?.translations.primaryTranslation().shortText ?? "",
                privacyPolicyLongtext: solution.consentItems.first { $0.type == .privacyPolicy}?.translations.primaryTranslation().longText ?? "",
                readMoreButton: solution.templateTexts.readMoreButton.primaryTranslation().text
            )
        
            self.onDataLoaded?(data)
        }
    }
`
Is a fix on the way?

**Comment by stonecrumbler** [comment]
fixed in v1.4.3
